name: camera
description: A Flutter plugin for getting information about and controlling the
  camera on Android and iOS. Supports previewing the camera feed, capturing images, capturing video,
  and streaming image buffers to dart.
version: 0.9.0
homepage: https://github.com/flutter/plugins/tree/master/packages/camera/camera
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  camera_platform_interface:
    git:
      url: https://github.com/jslattery26/flutter_packages/
      path: camera_platform_interface-1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.camera
        pluginClass: CameraPlugin
      ios:
        pluginClass: CameraPlugin

environment:
  sdk: ">=2.12.0 <3.0.0"
